name: Run Syndiesis.Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Syndiesis.Tests
      run: dotnet test Syndiesis.Tests/Syndiesis.Tests.csproj
