name: run-tests-windows

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  run:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests in Syndiesis.Tests
      run: dotnet test Syndiesis.Tests/Syndiesis.Tests.csproj
